spring.application.name=krupa_backend

# Read credentials injected from IntelliJ environment variables
spring.security.user.name=${ADMIN_USERNAME:boss}
spring.security.user.password=${ADMIN_PASSWORD}

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0000000

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

# ? Raise the limit for a single uploaded file (e.g., up to 50 Megabytes)
spring.servlet.multipart.max-file-size=50MB

# ? Raise the absolute ceiling for the entire multipart form request payload
spring.servlet.multipart.max-request-size=50MB